
export const ADD_NEW_CATEGORY = 'ADD_NEW_CATEGORY';
export const CHOOSE_CATEGORY = 'CHOOSE_CATEGORY';
export const CLEAR_CHOOSE = 'CLEAR_CHOOSE';
export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';